# Generated by Django 4.0.4 on 2022-05-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasecategory',
            old_name='name',
            new_name='category',
        ),
    ]
