# Generated by Django 4.0.4 on 2022-06-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasecategory',
            table='purchase_category',
        ),
    ]
