# Generated by Django 4.0.4 on 2022-06-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0004_alter_purchasecategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
            options={
                'db_table': 'budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetLimits',
            fields=[
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='django_tracker.budget')),
                ('spend_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'budget_limits',
                'managed': False,
            },
        ),
    ]
