# Generated by Django 4.0.4 on 2022-06-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0006_tokenblacklistblacklistedtoken_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenBlacklistBlacklistedtoken',
        ),
        migrations.DeleteModel(
            name='TokenBlacklistOutstandingtoken',
        ),
    ]
