# Generated by Django 4.0.4 on 2022-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0007_delete_tokenblacklistblacklistedtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetIncomes',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'budget_incomes',
                'managed': False,
            },
        ),
    ]
