# Generated by Django 4.0.4 on 2022-08-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0008_budgetincomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='budgetincomes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='budgetlimits',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purchasecategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taxcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transacttax',
            options={'managed': True},
        ),
    ]
