# Generated by Django 4.0.4 on 2022-08-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tracker', '0009_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.RemoveField(
            model_name='purchasecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='purchasecategory',
            name='id',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.authuser'),
        ),
        migrations.AddField(
            model_name='budgetincomes',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.budget'),
        ),
        migrations.AddField(
            model_name='budgetincomes',
            name='income_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetlimits',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetlimits',
            name='purc_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.purchasecategory'),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='purc_category_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='purc_category_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='spend_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.authuser'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='purc_category',
            field=models.ForeignKey(blank=True, db_column='purc_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.purchasecategory'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='transact',
            field=models.ForeignKey(db_column='transact_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.transactions'),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.authuser'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.budget'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.authuser'),
        ),
        migrations.AddField(
            model_name='transacttax',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacttax',
            name='tax',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.taxcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacttax',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.authuser'),
        ),
        migrations.AlterField(
            model_name='budgetlimits',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.budget'),
        ),
        migrations.AlterField(
            model_name='transacttax',
            name='transact',
            field=models.ForeignKey(db_column='transact_id', on_delete=django.db.models.deletion.DO_NOTHING, to='django_tracker.transactions'),
        ),
        migrations.AlterUniqueTogether(
            name='purchases',
            unique_together={('transact', 'purc_id')},
        ),
        migrations.AlterUniqueTogether(
            name='transacttax',
            unique_together={('transact', 'tax')},
        ),
        migrations.AddConstraint(
            model_name='budgetlimits',
            constraint=models.UniqueConstraint(fields=('budget', 'purc_category'), name='unique_budget_purc_category'),
        ),
        migrations.RemoveField(
            model_name='transacttax',
            name='user_id',
        ),
    ]
